namespace VRage.Game
{
    using System;

    public enum MyGenerationPropertiesEnum
    {
        Birth,
        Life,
        LifeVar,
        Velocity,
        VelocityDir,
        Angle,
        AngleVar,
        RotationSpeed,
        RotationSpeedVar,
        Radius,
        RadiusVar,
        Color,
        ColorVar,
        Material,
        ParticleType,
        Thickness,
        Enabled,
        EnableCustomRadius,
        EnableCustomVelocity,
        EnableCustomBirth,
        OnDie,
        OnLife,
        LODBirth,
        LODRadius,
        MotionInheritance,
        AlphaAnisotropic,
        Gravity,
        PivotRotation,
        Acceleration,
        AccelerationVar,
        AlphaCutout,
        BirthPerFrame,
        RadiusBySpeed,
        ColorIntensity,
        Pivot,
        PivotVar,
        PivotRotationVar,
        RotationReference,
        ArraySize,
        ArrayIndex,
        ArrayOffset,
        ArrayModulo,
        AccelerationReference,
        SoftParticleDistanceScale,
        BlendType,
        VelocityVar
    }
}

